package net.mrbogg.boggsblocks.datagen;

import net.minecraft.data.PackOutput;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.mrbogg.boggsblocks.BoggsBlocks;
import net.mrbogg.boggsblocks.block.ModBlocks;
import net.neoforged.neoforge.client.model.generators.BlockStateProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.registries.DeferredBlock;

public class ModBlockStateProvider extends BlockStateProvider {
    public ModBlockStateProvider(PackOutput output, ExistingFileHelper exFileHelper) {
        super(output, BoggsBlocks.MOD_ID, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {
        blockWithItem(ModBlocks.LIME_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.PURPLE_SHEETING);
        blockWithItem(ModBlocks.GREEN_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.LIGHT_GRAY_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.YELLOW_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.BLACK_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.GREEN_SHEETING);
        blockWithItem(ModBlocks.NORMAL_SLASHED);
        blockWithItem(ModBlocks.GREEN_SLASHED);
        blockWithItem(ModBlocks.WHITE_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.PINK_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BLUE_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.RED_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.PURPLE_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.GRAY_SHEETING);
        blockWithItem(ModBlocks.ORANGE_RIVETED);
        blockWithItem(ModBlocks.LIME_SLASHED);
        blockWithItem(ModBlocks.GREEN_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.ORANGE_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.WHITE_SHEETING);
        blockWithItem(ModBlocks.LIGHT_GRAY_SLASHED);
        blockWithItem(ModBlocks.RED_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.LIGHT_GRAY_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.GRAY_SLASHED);
        blockWithItem(ModBlocks.CYAN_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.NORMAL_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.LIME_SHEETING);
        blockWithItem(ModBlocks.PURPLE_RIVETED);
        blockWithItem(ModBlocks.PINK_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BLUE_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.YELLOW_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.LIME_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.ORANGE_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.CYAN_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.PURPLE_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BROWN_SHEETING);
        blockWithItem(ModBlocks.LIGHT_BLUE_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.RED_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.CYAN_SLASHED);
        blockWithItem(ModBlocks.MAGENTA_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.PURPLE_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.PINK_RIVETED);
        blockWithItem(ModBlocks.BLUE_RIVETED);
        blockWithItem(ModBlocks.BROWN_RIVETED);
        blockWithItem(ModBlocks.LIGHT_BLUE_RIVETED);
        blockWithItem(ModBlocks.LIGHT_BLUE_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.ORANGE_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.YELLOW_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.GRAY_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.BLUE_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.CYAN_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.NORMAL_SHEETING);
        blockWithItem(ModBlocks.WHITE_RIVETED);
        blockWithItem(ModBlocks.LIME_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.CYAN_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.PINK_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.ORANGE_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.RED_SLASHED);
        blockWithItem(ModBlocks.LIME_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BLACK_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.MAGENTA_SLASHED);
        blockWithItem(ModBlocks.LIGHT_GRAY_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.BLUE_SHEETING);
        blockWithItem(ModBlocks.BROWN_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.MAGENTA_SHEETING);
        blockWithItem(ModBlocks.BLUE_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.YELLOW_SLASHED);
        blockWithItem(ModBlocks.CYAN_SHEETING);
        blockWithItem(ModBlocks.BLACK_SLASHED);
        blockWithItem(ModBlocks.BLACK_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.PINK_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.ORANGE_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.WHITE_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.GRAY_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.RED_SHEETING);
        blockWithItem(ModBlocks.LIGHT_BLUE_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.GREEN_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.LIGHT_BLUE_SHEETING);
        blockWithItem(ModBlocks.BLACK_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.NORMAL_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.PURPLE_SLASHED);
        blockWithItem(ModBlocks.BLACK_SHEETING);
        blockWithItem(ModBlocks.ORANGE_SHEETING);
        blockWithItem(ModBlocks.LIME_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.MAGENTA_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.MAGENTA_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.LIGHT_GRAY_RIVETED);
        blockWithItem(ModBlocks.GRAY_RIVETED);
        blockWithItem(ModBlocks.ORANGE_SLASHED);
        blockWithItem(ModBlocks.LIME_RIVETED);
        blockWithItem(ModBlocks.PURPLE_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.NORMAL_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BROWN_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BLUE_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.LIGHT_GRAY_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.LIGHT_BLUE_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BLACK_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.RED_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.YELLOW_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.NORMAL_RIVETED);
        blockWithItem(ModBlocks.NORMAL_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.WHITE_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.GREEN_RIVETED);
        blockWithItem(ModBlocks.GREEN_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.YELLOW_RIVETED);
        blockWithItem(ModBlocks.BROWN_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.WHITE_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BLACK_RIVETED);
        blockWithItem(ModBlocks.YELLOW_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.LIGHT_GRAY_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.BROWN_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.WHITE_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.GRAY_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.LIGHT_GRAY_SHEETING);
        blockWithItem(ModBlocks.GREEN_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.MAGENTA_RIVETED);
        blockWithItem(ModBlocks.RED_RIVETED);
        blockWithItem(ModBlocks.GRAY_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.LIGHT_BLUE_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.WHITE_SLASHED);
        blockWithItem(ModBlocks.NORMAL_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.PINK_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.BROWN_COPPER_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.YELLOW_SHEETING);
        blockWithItem(ModBlocks.GRAY_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.CYAN_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.PURPLE_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.PINK_SLASHED);
        blockWithItem(ModBlocks.MAGENTA_IRON_WRAPPED_SLASHED);
        blockWithItem(ModBlocks.BROWN_SLASHED);
        blockWithItem(ModBlocks.BLUE_SLASHED);
        blockWithItem(ModBlocks.LIGHT_BLUE_SLASHED);
        blockWithItem(ModBlocks.RED_ANNEXED_RIVETED);
        blockWithItem(ModBlocks.PINK_SHEETING);
        blockWithItem(ModBlocks.MAGENTA_ANNEXED_SLASHED);
        blockWithItem(ModBlocks.CYAN_RIVETED);

        axisBlock((RotatedPillarBlock) ModBlocks.BLACK_RIVETED_PILLAR.get());
    }
    private void blockWithItem(DeferredBlock<?> deferredBlock) {
        simpleBlockWithItem(deferredBlock.get(), cubeAll(deferredBlock.get()));
    }
}
